name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests with ${{ matrix.python-version[0] }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - ['3.14t-dev', '3.14t']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version[0] }}

      - name: Install tox
        run: |
          pip install tox

      - name: Run test suite 100x (${{ matrix.python-version[0] }})
        run: |
          set -e
          for i in $(seq 1 100); do
            echo "=== Iteration $i/100 ==="
            tox -e ${{ matrix.python-version[1] }}
          done
